version: '3.8'

services:
  # MongoDB servisi
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db    # MongoDB verileri için kalıcı depolama

  # Redis servisi
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  # Uygulama servisi
  app:
    build: .    # Dockerfile'den imaj oluştur
    ports:
      - "3000:3000"    # Uygulamanın dış dünyaya hangi porttan açılacağı
    depends_on:
      - mongo    # Uygulamanın MongoDB'ye ve Redis'e bağımlılığı
      - redis
    environment:
      MONGO_URL: mongodb://mongo:27017/myapp    # MongoDB bağlantı URL'si
      REDIS_URL: redis://redis:6379    # Redis bağlantı URL'si

volumes:
  mongo-data:    # MongoDB veri birimi
